name = "SoftPosit"
uuid = "0775deef-a35f-56d7-82da-cfc52f91364d"
version = "0.3.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
BinaryProvider = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
